name: Playground dev

on:
  push:
    branches:
      - dev

jobs:
  playground:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: |
          echo "Hello world from dev"
