name: Playground main

on:
  workflow_dispatch:

jobs:
  playground:
    runs-on: ubuntu-latest
  
    steps:
      - name: Check branch
        run: |
          if [ "${{ github.ref }}" != "refs/heads/main" ]; then
            echo "This workflow can only be manually triggered on the main branch."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: |
          echo "Hello world from main"
